// Build out the combo box with the states
const states = [
  { val : "AL", text : "Alabama"},
  { val : "AK", text : "Alaska"},
  { val : "AZ", text : "Arizona"},
  { val : "AR", text : "Arkansas"},
  { val : "CA", text : "California"},
  { val : "CO", text : "Colorado"},
  { val : "CT", text : "Conneticut"},
  { val : "DE", text : "Deleware"},
  { val : "DC", text : "District of Columbia"},
  { val : "FL", text : "Florida"},
  { val : "GA", text : "Georgia"},
  { val : "HI", text : "Hawaii"},
  { val : "ID", text : "Idaho"},
  { val : "IL", text : "Illinois"},
  { val : "IN", text : "Indiana"},
  { val : "IA", text : "Iowa"},
  { val : "KS", text : "Kansas"},
  { val : "KY", text : "Kentucky"},
  { val : "LA", text : "Louisiana"},
  { val : "ME", text : "Maine"},
  { val : "MD", text : "Maryland"},
  { val : "MA", text : "Massachusetts"},
  { val : "MI", text : "Michigan"},
  { val : "MN", text : "Minnisota"},
  { val : "MS", text : "Mississippi"},
  { val : "MO", text : "Missouri"},
  { val : "MT", text : "Montana"},
  { val : "NE", text : "Nebraska"},
  { val : "NV", text : "Nevada"},
  { val : "NH", text : "New Hampshire"},
  { val : "NJ", text : "New Jersey"},
  { val : "NM", text : "New Mexico"},
  { val : "NY", text : "New York"},
  { val : "NC", text : "North Carolina"},
  { val : "ND", text : "North Dakota"},
  { val : "OH", text : "Ohio"},
  { val : "OK", text : "Oklahoma"},
  { val : "OR", text : "Oregon"},
  { val : "PA", text : "Pennsylvania"},
  { val : "RI", text : "Rhode Island"},
  { val : "SC", text : "South Carolina"},
  { val : "SD", text : "South Dakota"},
  { val : "TN", text : "Tennessee"},
  { val : "TX", text : "Texas"},
  { val : "UT", text : "Utah"},
  { val : "VT", text : "Vermont"},
  { val : "VA", text : "Virginia"},
  { val : "WA", text : "Washington"},
  { val : "WV", text : "West Virginia"},
  { val : "WI", text : "Wisconsin"},
  { val : "WY", text : "Wyoming"}
];

//builds the states combo box
$(states).each(function() {
  $("#state").append($('<option>').attr('value',this.val).text(this.text));
});
